### ISSUE TITLE
restore gRPC tutorial

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/solo-docs#259]
Users are asking for this tutorial https://github.com/solo-io/gloo/tree/old-master/example/grpc

As it is linked (broken link now) through this blog post: https://medium.com/solo-io/new-in-gloo-connect-json-clients-to-your-grpc-services-4724656ed15f

here's a partial yaml spec to get started:
```yaml
kubectl get vs default -n gloo-system -o yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    name: gloo-system.default
    routes:
    - matcher:
        exact: /shelves4
        methods:
        - GET
      routeAction:
        single:
          destinationSpec:
            grpc:
              function: ListShelves
              service: grpc-bookstore
          upstream:
            name: default-grpc-bookstore-8080
            namespace: gloo-system
```

[slack link](https://solo-io.slack.com/archives/C4RFYH51D/p1554981546004600)
